# GitHub Sponsors configuration
# Uncomment and add your funding links

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-collective-name
# ko_fi: your-kofi-username
# custom: ["https://your-website.com/donate", "https://buy-me-a-coffee.com/username"]
